### ISSUE TITLE
x_ops.so: undefined symbol: _ZN10tensorflow8str_util9LowercaseEN4absl11string_viewE

### ISSUE THREAD

**Issue by lorentz-wu** [didi/delta#10] opened 2019-08-09 08:50 UTC
Traceback (most recent call last):
  File "local/generate_mock_data.py", line 19, in <module>
    from delta.data.utils.test_utils import mock_a_text_file
  File "/home/xxx/study/delta/delta/data/utils/__init__.py", line 17, in <module>
    from delta.data.utils.common_utils import *
  File "/home/xxx/study/delta/delta/data/utils/common_utils.py", line 26, in <module>
    from delta.data.preprocess.text_ops import tokenize_label
  File "/home/xxx/study/delta/delta/data/preprocess/text_ops.py", line 22, in <module>
    from delta.layers.ops import py_x_ops
  File "/home/xxx/study/delta/delta/layers/__init__.py", line 27, in <module>
    from delta.layers.common_layers import *
  File "/home/xxx/study/delta/delta/layers/common_layers.py", line 22, in <module>
    from delta.data.feat import speech_ops
  File "/home/xxx/study/delta/delta/data/feat/__init__.py", line 17, in <module>
    from delta.data.feat import speech_ops
  File "/home/xxx/study/delta/delta/data/feat/speech_ops.py", line 25, in <module>
    from delta.layers.ops import py_x_ops
  File "/home/xxx/study/delta/delta/layers/ops/py_x_ops.py", line 27, in <module>
    tf.compat.v1.resource_loader.get_path_to_datafile('x_ops.so'))
  File "/home/xxx/anaconda3/envs/delta-py3.6-tf1.14/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/xxx/study/delta/delta/layers/ops/x_ops.so: undefined symbol: _ZN10tensorflow8str_util9LowercaseEN4absl11string_viewE

**Comment by mandubian** [comment] 2019-08-09 12:48
Same issue here...

**Comment by applenob** [comment] 2019-08-09 13:10
Currently, compilation of custom op with g++ 4.8 may cause this error. Please check your g++ version. If it's not g++ 4.8, please let us know.

You can use `conda install -c conda-forge cxx-compiler` to update the g++ version under your conda env.

then, compile custom op again：

```
pushd tools/
./install/install-ops.sh
popd
```

This issue has been added to our [FAQ](https://github.com/didi/delta/blob/master/docs/faq.md)

**Comment by applenob** [comment] 2019-08-09 13:12
We had add this part to our install script now: 

https://github.com/didi/delta/blob/b4d659e6dfd5d9a271907a8c96dd464b8c4fa450/tools/install/install-delta.sh#L60

**Comment by hankun11** [comment] 2019-08-12 02:55
@lorentz-wu  Is the problem fixed? We will close the issue if the problem is fixed. Thank you!

**Closed** 2019-08-14 06:53 UTC
Labels: install
